const profileStyles = {
  loading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '60vh',
    fontSize: 20,
    color: '#6366f1',
  },
  error: {
    color: '#ef4444',
    background: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: 12,
    padding: 24,
    margin: 32,
    textAlign: 'center' as const,
    fontSize: 18,
  },
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #fafbff, #f0f4ff)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative' as const,
    overflow: 'hidden',
    width: '100vw',
    padding: '0',
  },
  orbTop: {
    position: 'absolute' as const,
    top: '8%',
    right: '10%',
    width: '220px',
    height: '220px',
    background: 'radial-gradient(circle at 60% 40%, #818cf8 0%, #6366f1 100%)',
    borderRadius: '50%',
    filter: 'blur(60px)',
    opacity: 0.5,
    zIndex: 1,
  },
  orbBottom: {
    position: 'absolute' as const,
    bottom: '10%',
    left: '8%',
    width: '160px',
    height: '160px',
    background: 'radial-gradient(circle at 40% 60%, #a5b4fc 0%, #6366f1 100%)',
    borderRadius: '50%',
    filter: 'blur(40px)',
    opacity: 0.7,
    zIndex: 1,
  },
  main: {
    maxWidth: 800,
    width: '100%',
    zIndex: 2,
    position: 'relative' as const,
  },
  card: {
    maxWidth: '800px',
    width: '100%',
    background: '#fff',
    borderRadius: '18px',
    boxShadow: '0 2px 24px rgba(99,102,241,0.10)',
    padding: '40px',
    margin: '32px 0',
    border: '1px solid #e5e7eb',
    zIndex: 2,
    position: 'relative' as const,
  },
  heading: {
    fontSize: '2.2rem',
    fontWeight: 700,
    marginBottom: 8,
    textAlign: 'center' as const,
    color: '#6366f1',
  },
  subheading: {
    margin: '24px 0 32px 0',
    textAlign: 'center' as const,
    fontSize: 18,
    color: '#64748b',
    fontWeight: 500,
  },
  profileSection: {
    marginBottom: 32,
    padding: 24,
    background: '#f8fafc',
    borderRadius: 16,
    border: '1px solid #e5e7eb',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: '#374151',
    marginBottom: 16,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  profileGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 20,
    marginBottom: 24,
  },
  profileField: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: 600,
    color: '#6b7280',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  fieldValue: {
    fontSize: 16,
    color: '#374151',
    fontWeight: 500,
    padding: '8px 0',
  },
  emergencySection: {
    marginTop: 24,
    padding: 20,
    background: '#fef3cd',
    borderRadius: 12,
    border: '1px solid #f59e0b',
  },
  emergencyTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: '#92400e',
    marginBottom: 12,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  emergencyGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 16,
  },
  buttonPrimary: {
    background: '#6366f1',
    color: 'white',
    border: 'none',
    borderRadius: 12,
    padding: '12px 24px',
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 4px 20px rgba(99,102,241,0.15)',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  buttonSecondary: {
    background: 'white',
    color: '#6366f1',
    border: '2px solid #6366f1',
    borderRadius: 12,
    padding: '12px 24px',
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  buttonGroup: {
    display: 'flex',
    gap: 16,
    justifyContent: 'center',
    marginTop: 32,
  },
  formInput: {
    width: '100%',
    padding: '12px 16px',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    fontSize: 16,
    outline: 'none',
    transition: 'border-color 0.2s',
    background: 'white',
    color: '#1e293b', // dark text for visibility
    '::placeholder': {
      color: '#9ca3af',
      opacity: 1,
    },
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  avatarSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    marginBottom: 32,
    padding: 24,
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    borderRadius: 16,
    color: 'white',
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: '50%',
    background: 'white',
    color: '#6366f1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 48,
    fontWeight: 700,
    marginBottom: 16,
    boxShadow: '0 8px 32px rgba(0,0,0,0.1)',
  },
  displayName: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 4,
  },
  email: {
    fontSize: 16,
    opacity: 0.9,
  },
};

export default profileStyles;
