import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/providers/authProvider";
import { SeekerProvider } from "@/providers/seeker";
import { AssessmentProvider } from "@/providers/assessment";
import { JournalProvider } from "@/providers/journal";
import { MoodProvider } from "@/providers/mood";
import { ChatProvider } from "@/providers/chat";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <SeekerProvider>
        <AssessmentProvider>
          <JournalProvider>
            <MoodProvider>
              <ChatProvider>
                <html lang="en">
                  <body className={`${geistSans.variable} ${geistMono.variable}`}>
                    {children}
                  </body>
                </html>
              </ChatProvider>
            </MoodProvider>
          </JournalProvider>
        </AssessmentProvider>
      </SeekerProvider>
    </AuthProvider>
  );
}
