const dashboardStyles = {
  loading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '60vh',
    fontSize: 20,
    color: '#6366f1',
  },
  loadingIcon: {
    marginRight: 12,
  },
  error: {
    color: '#ef4444',
    background: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: 12,
    padding: 24,
    margin: 32,
    textAlign: 'center' as const,
    fontSize: 18,
  },
  errorIcon: {
    marginRight: 8,
  },
  main: {
    maxWidth: 600,
    width: '100%',
    zIndex: 2,
    position: 'relative' as const,
  },
  heading: {
    fontSize: '2.2rem',
    fontWeight: 700,
    marginBottom: 8,
    textAlign: 'center' as const,
    color: '#6366f1',
  },
  subheading: {
    margin: '24px 0 8px 0',
    textAlign: 'center' as const,
    fontSize: 18,
    color: '#64748b',
    fontWeight: 500,
  },
  grid: {
    margin: '24px 0',
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 18,
  },
  gridItem: {
    background: '#f8fafc',
    borderRadius: 10,
    padding: 16,
    textAlign: 'center' as const,
    boxShadow: '0 1px 4px #e0e7ef',
  },
  emoji: {
    fontSize: 22,
  },
  value: {
    fontSize: 18,
  },
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #fafbff, #f0f4ff)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative' as const,
    overflow: 'hidden',
    width: '100vw',
    padding: '0',
  },
  orbTop: {
    position: 'absolute' as const,
    top: '8%',
    right: '10%',
    width: '220px',
    height: '220px',
    background: 'radial-gradient(circle at 60% 40%, #818cf8 0%, #6366f1 100%)',
    borderRadius: '50%',
    filter: 'blur(60px)',
    opacity: 0.5,
    zIndex: 1,
  },
  orbBottom: {
    position: 'absolute' as const,
    bottom: '10%',
    left: '8%',
    width: '160px',
    height: '160px',
    background: 'radial-gradient(circle at 40% 60%, #a5b4fc 0%, #6366f1 100%)',
    borderRadius: '50%',
    filter: 'blur(40px)',
    opacity: 0.7,
    zIndex: 1,
  },
  card: {
    maxWidth: '600px',
    width: '100%',
    background: '#fff',
    borderRadius: '18px',
    boxShadow: '0 2px 24px rgba(99,102,241,0.10)',
    padding: '32px',
    margin: '32px 0',
    border: '1px solid #e5e7eb',
    zIndex: 2,
    position: 'relative' as const,
  },
};

export default dashboardStyles;
