const chatModalStyles = {
  container: {
    position: 'fixed',
    bottom: 0,
    right: 0,
    width: 370,
    maxWidth: '100vw',
    height: 500,
    background: '#fff',
    boxShadow: '0 4px 32px rgba(99,102,241,0.18)',
    borderRadius: '18px 18px 0 0',
    zIndex: 2000,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    fontFamily: 'Inter, Arial, sans-serif',
  },
  header: {
    padding: '16px',
    borderBottom: '1px solid #eee',
    background: '#6366f1',
    color: 'white',
    fontWeight: 600,
    fontSize: '1.1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  headerIcon: {
    fontSize: 22,
    marginRight: 6,
  },
  headerButton: {
    background: 'white',
    color: '#6366f1',
    border: 'none',
    borderRadius: 8,
    fontWeight: 600,
    fontSize: 14,
    padding: '4px 12px',
    marginRight: 8,
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  closeButton: {
    background: 'none',
    border: 'none',
    color: 'white',
    fontSize: 22,
    cursor: 'pointer',
  },
  messages: {
    flex: 1,
    padding: '16px',
    overflowY: 'auto',
    background: '#f8fafc',
  },
  messageBubble: {
    display: 'inline-block',
    borderRadius: 10,
    padding: '10px 16px',
    maxWidth: '80%',
    fontSize: 15,
  },
  userBubble: {
    background: '#6366f1',
    color: 'white',
    boxShadow: '0 2px 8px rgba(99,102,241,0.10)',
  },
  botBubble: {
    background: '#e0e7ff',
    color: '#333',
  },
  form: {
    display: 'flex',
    padding: '14px',
    borderTop: '1px solid #eee',
    background: '#fff',
    gap: 8,
  },
  input: {
    flex: 1,
    borderRadius: 10,
    border: '1px solid #ccc',
    padding: '10px 14px',
    fontSize: 15,
    outline: 'none',
    boxShadow: '0 2px 8px rgba(99,102,241,0.05)',
  },
  sendButton: {
    background: '#6366f1',
    color: 'white',
    border: 'none',
    borderRadius: 10,
    padding: '10px 18px',
    fontWeight: 600,
    fontSize: 15,
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(99,102,241,0.10)',
    transition: 'background 0.2s',
  },
};

export default chatModalStyles;
