const assessmentStyles = {
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #6366f1 0%, #a5b4fc 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
    width: '100vw',
    padding: '0',
  },
  orbTop: {
    position: 'absolute',
    top: '8%',
    right: '10%',
    width: '220px',
    height: '220px',
    background: 'radial-gradient(circle at 60% 40%, #818cf8 0%, #6366f1 100%)',
    borderRadius: '50%',
    filter: 'blur(60px)',
    opacity: 0.5,
    zIndex: 1,
  },
  orbBottom: {
    position: 'absolute',
    bottom: '10%',
    left: '8%',
    width: '160px',
    height: '160px',
    background: 'radial-gradient(circle at 40% 60%, #a5b4fc 0%, #6366f1 100%)',
    borderRadius: '50%',
    filter: 'blur(40px)',
    opacity: 0.7,
    zIndex: 1,
  },
  card: {
    maxWidth: '600px',
    width: '100%',
    background: '#fff',
    borderRadius: '18px',
    boxShadow: '0 2px 24px rgba(99,102,241,0.10)',
    padding: '32px',
    margin: '32px 0',
    border: '1px solid #e5e7eb',
    zIndex: 2,
    position: 'relative',
  },
  progressBarBg: {
    width: '100%',
    background: '#f3f4f6',
    borderRadius: '8px',
    height: '10px',
    marginBottom: '24px',
  },
  progressBar: {
    background: '#6366f1',
    height: '100%',
    borderRadius: '8px',
    transition: 'width 0.3s',
  },
  questionCard: {
    background: '#f8fafc',
    borderRadius: '12px',
    boxShadow: '0 2px 12px rgba(0,0,0,0.04)',
    padding: '24px',
    marginBottom: '12px',
    border: '1px solid #e5e7eb',
  },
  reviewCard: {
    background: '#f9fafb',
    borderRadius: '12px',
    boxShadow: '0 2px 12px rgba(0,0,0,0.04)',
    padding: '24px',
    border: '1px solid #e5e7eb',
  },
  buttonPrimary: {
    padding: '12px 32px',
    borderRadius: '24px',
    background: '#6366f1',
    color: '#fff',
    fontWeight: 600,
    fontSize: '18px',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(99,102,241,0.08)',
    transition: 'background 0.2s',
  },
  buttonSecondary: {
    padding: '8px 24px',
    borderRadius: '24px',
    background: '#e5e7eb',
    color: '#6366f1',
    fontWeight: 600,
    fontSize: '16px',
    border: 'none',
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  buttonDisabled: {
    background: '#e5e7eb',
    color: '#888',
    cursor: 'not-allowed',
  },
};

export default assessmentStyles;
