name: CI/CD for backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed for GHCR push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: aspnet-core/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mindmate-backend:latest

  deploy:
    name: Notify Render
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"
